### ISSUE TITLE
CSS and JS files got blocked over HTTPS

### ISSUE THREAD

**Issue by l3ouu4n9** [hankhplee/hankhplee.github.io#1]
css and js files are blocked in `https://hankhplee.com/` due to requesting http contents over https.

I think putting `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` in `<head></head>` may solve the issue, not sure about that though 🤪

**Comment by hankhplee** [comment]
hey @l3ouu4n9! thanks for the catch :)
